"""Type stub for the pybind11 graph_sampler extension.

The compiled module is produced by the CMake target `graph_sampler`.
Users occupy [0, num_users); movies occupy [num_users, num_nodes).
Construction takes local (user_id, movie_id) pairs, not global movie IDs.
parse_movielens_100k accepts in-memory tab-separated u.data text only.
"""

from collections.abc import Sequence

class GraphError(ValueError):
    """Invalid graph construction, parse request, or sample request."""

class MovieLens100kInteraction:
    @property
    def user_id(self) -> int: ...
    @property
    def movie_id(self) -> int: ...
    @property
    def rating(self) -> int: ...
    @property
    def timestamp(self) -> int: ...

class MovieLens100kRatings:
    @property
    def num_users(self) -> int: ...
    @property
    def num_movies(self) -> int: ...
    @property
    def interactions(self) -> list[MovieLens100kInteraction]: ...
    @property
    def user_source_ids(self) -> list[int]: ...
    @property
    def movie_source_ids(self) -> list[int]: ...
    def local_pairs(self) -> list[tuple[int, int]]: ...

def parse_movielens_100k(text: str) -> MovieLens100kRatings: ...

class BipartiteCSR:
    def __init__(
        self,
        num_users: int,
        num_movies: int,
        interactions: Sequence[tuple[int, int]],
    ) -> None: ...
    @property
    def num_users(self) -> int: ...
    @property
    def num_movies(self) -> int: ...
    @property
    def num_nodes(self) -> int: ...
    def degree(self, node_id: int) -> int: ...
    def sample_neighbors(self, node_id: int, k: int, seed: int) -> list[int]: ...
    def offsets(self) -> list[int]: ...
    def neighbors(self) -> list[int]: ...
